### ISSUE TITLE
Rewrite Collection Thumbnails to Have Default Values

### ISSUE THREAD

**Issue by NotNorgaz** [Aradax/aradax.github.io#4]
http://aradax.github.io/dv/collections/page

**Comment by mitchiiii** [comment]
Thinking of changing the formatting to the following:
```
{
    collection: "",
    collection_id: "",
    contributing_authors: [
        {name: "", uuid: "", anthr: false},
    ],
    front_map: [ {name: "", id: "", (genre): true} ],
    left_map: [ {name: "", id: "", (genre): true} ],
    right_map: [ {name: "", id: "", (genre): true} ],
    listed_maps: [
        {name: "", id: "", (genre): true},
    ],
},
```
Doing it this way would remove the need for `no_featured` as if there is nothing in `listed_maps` it will return false anyway, and disable the list.

**Comment by mitchiiii** [comment]
Just pushed changes described above to http://aradax.github.io/dv/collections/page. You can see the changes I made to the formatting [here](https://github.com/Aradax/dv/blob/gh-pages/collections/collections.js) under the `proto_02` collections.
